# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ingresarValores.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(638, 474)
        MainWindow.setMinimumSize(QtCore.QSize(484, 0))
        MainWindow.setMaximumSize(QtCore.QSize(638, 474))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0         rgba(91, 91, 91, 255), stop:1 rgba(118, 118, 118, 255));\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(180, 40, 271, 31))
        self.titulo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.titulo.setStyleSheet("font: 75 20pt \"Bahnschrift\";\n"
"color: rgb(255, 255, 255);")
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 100, 81, 16))
        self.label.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: #55ffff;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 180, 81, 16))
        self.label_2.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: #55ffff;\n"
"")
        self.label_2.setObjectName("label_2")
        self.calcular = QtWidgets.QPushButton(self.centralwidget)
        self.calcular.setGeometry(QtCore.QRect(220, 340, 81, 31))
        self.calcular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calcular.setStyleSheet("border: 2px solid #55ffff;\n"
"font: 75 12pt \"Bahnschrift Condensed\";\n"
"background-color: rgb(150, 150, 150, 50%);\n"
"color: white;\n"
"border-radius: 7px;")
        self.calcular.setObjectName("calcular")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 260, 81, 16))
        self.label_3.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: #55ffff;\n"
"")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(270, 120, 101, 31))
        self.textEdit.setStyleSheet("border: 2px solid #55ffff;\n"
"background-color: rgb(150, 150, 150, 50%);\n"
"color: white;\n"
"border-radius: 7px;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(270, 200, 101, 31))
        self.textEdit_2.setStyleSheet("border: 2px solid #55ffff;\n"
"background-color: rgb(150, 150, 150, 50%);\n"
"color: white;\n"
"border-radius: 7px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(270, 280, 101, 31))
        self.textEdit_3.setStyleSheet("border: 2px solid #55ffff;\n"
"background-color: rgb(150, 150, 150, 50%);\n"
"color: white;\n"
"border-radius: 7px;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.calcular_2 = QtWidgets.QPushButton(self.centralwidget)
        self.calcular_2.setGeometry(QtCore.QRect(330, 340, 81, 31))
        self.calcular_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calcular_2.setStyleSheet("border: 2px solid #55ffff;\n"
"font: 75 12pt \"Bahnschrift Condensed\";\n"
"background-color: rgb(150, 150, 150, 50%);\n"
"color: white;\n"
"border-radius: 7px;")
        self.calcular_2.setObjectName("calcular_2")
        self.mensaje = QtWidgets.QLabel(self.centralwidget)
        self.mensaje.setGeometry(QtCore.QRect(180, 390, 291, 20))
        self.mensaje.setStyleSheet("color: rgb(255, 255, 255);")
        self.mensaje.setText("")
        self.mensaje.setObjectName("mensaje")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo.setText(_translate("MainWindow", "Optimización de modelos"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Numero 1</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Numero 2</p></body></html>"))
        self.calcular.setText(_translate("MainWindow", "Calcular"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Resultado</p></body></html>"))
        self.calcular_2.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
